# Generated by Django 2.0.2 on 2020-07-16 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qcreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=100)),
                ('aspect', models.CharField(max_length=100)),
                ('codec', models.CharField(max_length=100)),
                ('bit', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('conmments', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
