# Generated by Django 2.0.2 on 2020-07-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcrep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcreport',
            name='framesPerSecond',
            field=models.CharField(choices=[('23.98P', '23.98 Progressive'), ('23.98I', '23.98 Interlaced'), ('29.97P', '29.97 Progressive'), ('29.97I', '29.97 Interlaced'), ('25P', '25 Progressive'), ('25I', '25 Interlaced'), ('24P', '24 Progressive'), ('59.94I', '59.94I')], default=23.98, max_length=100),
        ),
    ]
