# Generated by Django 2.0.2 on 2020-07-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcrep', '0003_qcreport_tecreject'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcreport',
            name='missing_elements',
            field=models.CharField(choices=[('MT', 'Movie Title'), ('CR', 'Initial Credits'), ('FR', 'Final Roller'), ('EN', 'Episode Number')], default='EN', max_length=100),
        ),
    ]
