# Generated by Django 3.0.8 on 2020-07-25 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qcrep', '0006_userschart'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcreport',
            name='image',
            field=models.ImageField(default='None', upload_to='qcreports_pics'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='author',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
