# Generated by Django 3.0.8 on 2020-07-25 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qcrep', '0009_auto_20200725_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcreport',
            name='qc_duedate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
